### ISSUE TITLE
Linking fails for TRACK_PRIMARY=ON

### ISSUE THREAD

**Issue by op3** [uga-uga/nutr#10]
The `TRACK_PRIMARY=ON` compile-time option is broken since ad55df2c3e6c2bd70712495f8fd109dfede3cd4b:

```
$ mkdir -p build && cmake -S . -B build -DTRACK_PRIMARY=ON && cmake --build build
[…]
[ 86%] Linking CXX executable ../../../../2021-02-16_to_2021-04-10/gps_2021-02-16_to_2021-04-10
/nfs/cloud/home/user/.local/share/conda/envs/g11/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../../../sensitive_detector/libanalysisManager.a(AnalysisManager.cc.o): in function `AnalysisManager::FillNtupleColumns(G4GenericAnalysisManager*, G4Event const*, std::vector<std::shared_ptr<G4VHit>, std::allocator<std::shared_ptr<G4VHit> > >&)':
AnalysisManager.cc:(.text._ZN15AnalysisManager17FillNtupleColumnsEP24G4GenericAnalysisManagerPK7G4EventRSt6vectorISt10shared_ptrI6G4VHitESaIS8_EE+0x7e): undefined reference to `G4PrimaryVertex::GetPrimary(int) const'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/geometry/clover_array/2021-02-16_to_2021-04-10/CMakeFiles/gps_2021-02-16_to_2021-04-10.dir/build.make:191: 2021-02-16_to_2021-04-10/gps_2021-02-16_to_2021-04-10] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3762: src/geometry/clover_array/2021-02-16_to_2021-04-10/CMakeFiles/gps_2021-02-16_to_2021-04-10.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Tested for geant4 11.0.3 and 11.1.1.

I assume analysisManager has to be linked against `Geant4::G4particles`.
